# Generated by Django 3.2.9 on 2021-12-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emp_code',
            new_name='reg_num',
        ),
    ]
