# Generated by Django 3.2.9 on 2021-12-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emp_code_student_reg_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stream',
            new_name='title',
        ),
    ]
