# Generated by Django 4.0.2 on 2022-02-27 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211205_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
